name: poppler-utils-timmd909 # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: poppler v.90.1 release July 11, 2020 # 79 char long summary
description: |
  Snap version of the latest poppler for use with legacy Ubuntu servers

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  poppler:
    plugin: cmake
    source: https://gitlab.freedesktop.org/poppler/poppler.git
    stage-packages:
      - fontconfig
      - libcairo2
      - libcurl4
      - libfontconfig1
      - libfreetype6
      - liblcms2-2
      - liblcms2-utils
      - libnss3
      - libnss3-tools
      - libopenjp2-7
      - libopenjpip-dec-server
      - libopenjpip7
      - libpng-tools
      - libpng16-16
      - libstdc++6
      - libtiff-tools
      - poppler-data  # This may be a problem and may need to be built manually
    build-packages:
      - build-essential
      - cmake
      - g++
      - libcairo2-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - liblcms2-dev
      - libnss3-dev
      - libopenjp2-7-dev
      - libtiff-dev
      - make
      - pkgconf
