name: poppler-utils-timmd909 # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.2' # just for humans
summary: poppler v.90.1 release July 11, 2020 # 79 char long summary
description: |
  Snap version of the latest poppler for use with legacy Ubuntu servers.

  Since this is a bunch of command line tools, it needs classic confinement.

  I like using some [poppler](https://poppler.freedesktop.org/) utilities
  for automating PDF regression tests. Unfortunately after Ubuntu 18.04,
  the version of `poppler-utils` changes causing minor variations everywhere.

# grade: devel
grade: stable # must be 'stable' to release into candidate/stable channels
# confinement: strict
confinement: classic

# -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- #

apps:
  pdfattach:
    command: bin/pdfattach
  pdffonts:
    command: bin/pdffonts
  pdfinfo:
    command: bin/pdfinfo
  pdfsig:
    command: bin/pdfsig
  pdftohtml:
    command: bin/pdftops
  pdftops:
    command: bin/pdftops
  pdfunite:
    command: bin/pdfunite
  pdfdetach:
    command: bin/pdfdetach
  pdfimages:
    command: bin/pdfimages
  pdfseparate:
    command: bin/pdfseparate
  pdftocairo:
    command: bin/pdftocairo
  pdftoppm:
    command: bin/pdftoppm
  pdftotext:
    command: bin/pdftotext

# -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- #

parts:
  poppler-data:
    plugin: make
    source: https://gitlab.freedesktop.org/poppler/poppler-data.git
    make-parameters:
      - prefix=/usr

  poppler:
    plugin: cmake
    source: https://gitlab.freedesktop.org/poppler/poppler.git
    stage-packages:
      - fontconfig
      - libcairo2
      - libcurl4
      - libfontconfig1
      - libfreetype6
      - liblcms2-2
      - liblcms2-utils
      - libnss3
      - libnss3-tools
      - libopenjp2-7
      - libopenjpip-dec-server
      - libopenjpip7
      - libpng-tools
      - libpng16-16
      - libstdc++6
      - libtiff-tools
    build-packages:
      - build-essential
      - cmake
      - g++
      - libboost-all-dev
      - libcairo2-dev
      - libcurl4-openssl-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - liblcms2-dev
      - libnss3-dev
      - libopenjp2-7-dev
      - libtiff-dev
      - libtool
      - make
      - pkgconf
